// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEiru9nktPiPMWiocNiXzsaO1Pt_2Ehic',
    appId: '1:561423568846:web:7d94f8065bc1818e71a59f',
    messagingSenderId: '561423568846',
    projectId: 'fir-iti-fdbe9',
    authDomain: 'fir-iti-fdbe9.firebaseapp.com',
    storageBucket: 'fir-iti-fdbe9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8HEAX6dPoLXPWbBkoQseqRQBFTGbJU8Y',
    appId: '1:561423568846:android:7709e5f4d30d686e71a59f',
    messagingSenderId: '561423568846',
    projectId: 'fir-iti-fdbe9',
    storageBucket: 'fir-iti-fdbe9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEiru9nktPiPMWiocNiXzsaO1Pt_2Ehic',
    appId: '1:561423568846:web:6d4effa0e435333871a59f',
    messagingSenderId: '561423568846',
    projectId: 'fir-iti-fdbe9',
    authDomain: 'fir-iti-fdbe9.firebaseapp.com',
    storageBucket: 'fir-iti-fdbe9.firebasestorage.app',
  );
}
